# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(840, 611)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.filter_list_listWidget = QtGui.QListWidget(self.centralwidget)
        self.filter_list_listWidget.setObjectName(_fromUtf8("filter_list_listWidget"))
        item = QtGui.QListWidgetItem()
        self.filter_list_listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.filter_list_listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.filter_list_listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.filter_list_listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.filter_list_listWidget.addItem(item)
        self.gridLayout_2.addWidget(self.filter_list_listWidget, 0, 0, 1, 1)
        self.edit_woman_pushButton = QtGui.QPushButton(self.centralwidget)
        self.edit_woman_pushButton.setObjectName(_fromUtf8("edit_woman_pushButton"))
        self.gridLayout_2.addWidget(self.edit_woman_pushButton, 2, 0, 1, 1)
        self.delete_woman_pushButton = QtGui.QPushButton(self.centralwidget)
        self.delete_woman_pushButton.setObjectName(_fromUtf8("delete_woman_pushButton"))
        self.gridLayout_2.addWidget(self.delete_woman_pushButton, 3, 0, 1, 1)
        self.add_woman_pushButton = QtGui.QPushButton(self.centralwidget)
        self.add_woman_pushButton.setObjectName(_fromUtf8("add_woman_pushButton"))
        self.gridLayout_2.addWidget(self.add_woman_pushButton, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.study_level_comboBox = QtGui.QComboBox(self.groupBox)
        self.study_level_comboBox.setObjectName(_fromUtf8("study_level_comboBox"))
        self.study_level_comboBox.addItem(_fromUtf8(""))
        self.study_level_comboBox.addItem(_fromUtf8(""))
        self.study_level_comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.study_level_comboBox, 2, 4, 1, 1)
        self.phone_number_Edit = QtGui.QLineEdit(self.groupBox)
        self.phone_number_Edit.setObjectName(_fromUtf8("phone_number_Edit"))
        self.gridLayout.addWidget(self.phone_number_Edit, 2, 9, 1, 1)
        self.address_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.address_lineEdit.setObjectName(_fromUtf8("address_lineEdit"))
        self.gridLayout.addWidget(self.address_lineEdit, 1, 4, 1, 6)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 8, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 10, 1, 1)
        self.income_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.income_lineEdit.setObjectName(_fromUtf8("income_lineEdit"))
        self.gridLayout.addWidget(self.income_lineEdit, 3, 4, 1, 1)
        self.woman_data_of_birth_dateEdit = QtGui.QDateEdit(self.groupBox)
        self.woman_data_of_birth_dateEdit.setCalendarPopup(True)
        self.woman_data_of_birth_dateEdit.setObjectName(_fromUtf8("woman_data_of_birth_dateEdit"))
        self.gridLayout.addWidget(self.woman_data_of_birth_dateEdit, 0, 4, 1, 1)
        self.health_status_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.health_status_lineEdit.setObjectName(_fromUtf8("health_status_lineEdit"))
        self.gridLayout.addWidget(self.health_status_lineEdit, 3, 6, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 5, 1, 1)
        self.marital_status_comboBox = QtGui.QComboBox(self.groupBox)
        self.marital_status_comboBox.setObjectName(_fromUtf8("marital_status_comboBox"))
        self.marital_status_comboBox.addItem(_fromUtf8(""))
        self.marital_status_comboBox.addItem(_fromUtf8(""))
        self.marital_status_comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.marital_status_comboBox, 2, 6, 1, 2)
        self.last_name_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.last_name_lineEdit.setObjectName(_fromUtf8("last_name_lineEdit"))
        self.gridLayout.addWidget(self.last_name_lineEdit, 0, 6, 1, 2)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 10, 1, 1)
        self.first_name_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.first_name_lineEdit.setObjectName(_fromUtf8("first_name_lineEdit"))
        self.gridLayout.addWidget(self.first_name_lineEdit, 0, 9, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 8, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 10, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 10, 1, 1)
        self.occupation_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.occupation_lineEdit.setObjectName(_fromUtf8("occupation_lineEdit"))
        self.gridLayout.addWidget(self.occupation_lineEdit, 3, 9, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 4, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 5, 1, 1)
        self.need_transportation_checkBox = QtGui.QCheckBox(self.groupBox)
        self.need_transportation_checkBox.setObjectName(_fromUtf8("need_transportation_checkBox"))
        self.gridLayout.addWidget(self.need_transportation_checkBox, 5, 9, 1, 2)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 8, 1, 1)
        self.reason_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.reason_lineEdit.setObjectName(_fromUtf8("reason_lineEdit"))
        self.gridLayout.addWidget(self.reason_lineEdit, 4, 6, 1, 2)
        self.need_training_checkBox = QtGui.QCheckBox(self.groupBox)
        self.need_training_checkBox.setObjectName(_fromUtf8("need_training_checkBox"))
        self.gridLayout.addWidget(self.need_training_checkBox, 4, 9, 1, 2)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 4, 8, 1, 1)
        self.training_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.training_lineEdit.setObjectName(_fromUtf8("training_lineEdit"))
        self.gridLayout.addWidget(self.training_lineEdit, 4, 4, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.edit_child_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.edit_child_pushButton.setObjectName(_fromUtf8("edit_child_pushButton"))
        self.gridLayout_4.addWidget(self.edit_child_pushButton, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 0, 1, 1, 1)
        self.delete_child_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.delete_child_pushButton.setObjectName(_fromUtf8("delete_child_pushButton"))
        self.gridLayout_4.addWidget(self.delete_child_pushButton, 5, 1, 1, 1)
        self.children_listWidget = QtGui.QListWidget(self.groupBox_2)
        self.children_listWidget.setObjectName(_fromUtf8("children_listWidget"))
        item = QtGui.QListWidgetItem()
        self.children_listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.children_listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.children_listWidget.addItem(item)
        self.gridLayout_4.addWidget(self.children_listWidget, 1, 1, 2, 1)
        self.add_child_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.add_child_pushButton.setObjectName(_fromUtf8("add_child_pushButton"))
        self.gridLayout_4.addWidget(self.add_child_pushButton, 3, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.dateEdit_2 = QtGui.QDateEdit(self.groupBox_3)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.gridLayout_5.addWidget(self.dateEdit_2, 1, 2, 1, 1)
        self.child_date_of_birth_label = QtGui.QLabel(self.groupBox_3)
        self.child_date_of_birth_label.setObjectName(_fromUtf8("child_date_of_birth_label"))
        self.gridLayout_5.addWidget(self.child_date_of_birth_label, 1, 3, 1, 1)
        self.child_first_name_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.child_first_name_lineEdit.setObjectName(_fromUtf8("child_first_name_lineEdit"))
        self.gridLayout_5.addWidget(self.child_first_name_lineEdit, 0, 2, 1, 1)
        self.child_last_name_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.child_last_name_lineEdit.setObjectName(_fromUtf8("child_last_name_lineEdit"))
        self.gridLayout_5.addWidget(self.child_last_name_lineEdit, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 5, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 0, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.english_course_checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.english_course_checkBox.setObjectName(_fromUtf8("english_course_checkBox"))
        self.gridLayout_6.addWidget(self.english_course_checkBox, 0, 1, 1, 1)
        self.arabic_course_checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.arabic_course_checkBox.setObjectName(_fromUtf8("arabic_course_checkBox"))
        self.gridLayout_6.addWidget(self.arabic_course_checkBox, 0, 0, 1, 1)
        self.math_course_checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.math_course_checkBox.setObjectName(_fromUtf8("math_course_checkBox"))
        self.gridLayout_6.addWidget(self.math_course_checkBox, 0, 2, 1, 1)
        self.islamic_course_checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.islamic_course_checkBox.setObjectName(_fromUtf8("islamic_course_checkBox"))
        self.gridLayout_6.addWidget(self.islamic_course_checkBox, 1, 0, 1, 1)
        self.science_course_checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.science_course_checkBox.setObjectName(_fromUtf8("science_course_checkBox"))
        self.gridLayout_6.addWidget(self.science_course_checkBox, 1, 1, 1, 1)
        self.computer_course_checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.computer_course_checkBox.setObjectName(_fromUtf8("computer_course_checkBox"))
        self.gridLayout_6.addWidget(self.computer_course_checkBox, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 4, 0, 1, 4)
        self.child_study_level_comboBox = QtGui.QComboBox(self.groupBox_3)
        self.child_study_level_comboBox.setObjectName(_fromUtf8("child_study_level_comboBox"))
        self.child_study_level_comboBox.addItem(_fromUtf8(""))
        self.child_study_level_comboBox.addItem(_fromUtf8(""))
        self.child_study_level_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.child_study_level_comboBox, 2, 0, 1, 2)
        self.child_study_level_label = QtGui.QLabel(self.groupBox_3)
        self.child_study_level_label.setObjectName(_fromUtf8("child_study_level_label"))
        self.gridLayout_5.addWidget(self.child_study_level_label, 2, 2, 1, 2)
        self.hobbies_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.hobbies_lineEdit.setObjectName(_fromUtf8("hobbies_lineEdit"))
        self.gridLayout_5.addWidget(self.hobbies_lineEdit, 6, 0, 1, 3)
        self.child_need_transportation_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.child_need_transportation_checkBox.setObjectName(_fromUtf8("child_need_transportation_checkBox"))
        self.gridLayout_5.addWidget(self.child_need_transportation_checkBox, 5, 2, 1, 2)
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 3, 2, 1, 2)
        self.grade_last_year_comboBox = QtGui.QComboBox(self.groupBox_3)
        self.grade_last_year_comboBox.setObjectName(_fromUtf8("grade_last_year_comboBox"))
        self.grade_last_year_comboBox.addItem(_fromUtf8(""))
        self.grade_last_year_comboBox.addItem(_fromUtf8(""))
        self.grade_last_year_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.grade_last_year_comboBox, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 6, 3, 1, 1)
        self.save_child_pushButton = QtGui.QPushButton(self.groupBox_3)
        self.save_child_pushButton.setObjectName(_fromUtf8("save_child_pushButton"))
        self.gridLayout_5.addWidget(self.save_child_pushButton, 7, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 5, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 6, 4, 1, 7)
        self.save_woman_pushButton = QtGui.QPushButton(self.groupBox)
        self.save_woman_pushButton.setObjectName(_fromUtf8("save_woman_pushButton"))
        self.gridLayout.addWidget(self.save_woman_pushButton, 7, 5, 1, 4)
        self.available_time_comboBox = QtGui.QComboBox(self.groupBox)
        self.available_time_comboBox.setObjectName(_fromUtf8("available_time_comboBox"))
        self.available_time_comboBox.addItem(_fromUtf8(""))
        self.available_time_comboBox.addItem(_fromUtf8(""))
        self.available_time_comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.available_time_comboBox, 5, 4, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 5, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.groupBox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        __sortingEnabled = self.filter_list_listWidget.isSortingEnabled()
        self.filter_list_listWidget.setSortingEnabled(False)
        item = self.filter_list_listWidget.item(0)
        item.setText(_translate("MainWindow", "woman name1", None))
        item = self.filter_list_listWidget.item(1)
        item.setText(_translate("MainWindow", "woman name2", None))
        item = self.filter_list_listWidget.item(2)
        item.setText(_translate("MainWindow", "woman name3", None))
        item = self.filter_list_listWidget.item(3)
        item.setText(_translate("MainWindow", "woman name4", None))
        item = self.filter_list_listWidget.item(4)
        item.setText(_translate("MainWindow", "woman name5", None))
        self.filter_list_listWidget.setSortingEnabled(__sortingEnabled)
        self.edit_woman_pushButton.setText(_translate("MainWindow", "تعديل", None))
        self.delete_woman_pushButton.setText(_translate("MainWindow", "حذف", None))
        self.add_woman_pushButton.setText(_translate("MainWindow", "إضافة", None))
        self.groupBox.setTitle(_translate("MainWindow", "معلومات شخصية", None))
        self.study_level_comboBox.setItemText(0, _translate("MainWindow", "New Item", None))
        self.study_level_comboBox.setItemText(1, _translate("MainWindow", "New Item", None))
        self.study_level_comboBox.setItemText(2, _translate("MainWindow", "New Item", None))
        self.label_6.setText(_translate("MainWindow", "الحالة الإجتماعية:", None))
        self.label_9.setText(_translate("MainWindow", "المهنة:", None))
        self.label_7.setText(_translate("MainWindow", "المستوى الدراسي", None))
        self.marital_status_comboBox.setItemText(0, _translate("MainWindow", "New Item", None))
        self.marital_status_comboBox.setItemText(1, _translate("MainWindow", "New Item", None))
        self.marital_status_comboBox.setItemText(2, _translate("MainWindow", "New Item", None))
        self.label.setText(_translate("MainWindow", "الاسم:", None))
        self.label_2.setText(_translate("MainWindow", "اللقب", None))
        self.label_3.setText(_translate("MainWindow", "تاريخ الميلاد:", None))
        self.label_4.setText(_translate("MainWindow", "العنوان:", None))
        self.label_5.setText(_translate("MainWindow", "الهاتف:", None))
        self.label_13.setText(_translate("MainWindow", "نوع التدريب:", None))
        self.label_10.setText(_translate("MainWindow", "الحالة الاقتصادية", None))
        self.need_transportation_checkBox.setText(_translate("MainWindow", "تحتاج للمواصلات", None))
        self.label_8.setText(_translate("MainWindow", "الحالة الصحية", None))
        self.need_training_checkBox.setText(_translate("MainWindow", " ترغب في التدريب", None))
        self.label_12.setText(_translate("MainWindow", "السبب:", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "الأولاد:", None))
        self.edit_child_pushButton.setText(_translate("MainWindow", "تعديل", None))
        self.label_14.setText(_translate("MainWindow", "أسماء الاولاد:", None))
        self.delete_child_pushButton.setText(_translate("MainWindow", "حذف", None))
        __sortingEnabled = self.children_listWidget.isSortingEnabled()
        self.children_listWidget.setSortingEnabled(False)
        item = self.children_listWidget.item(0)
        item.setText(_translate("MainWindow", "child1", None))
        item = self.children_listWidget.item(1)
        item.setText(_translate("MainWindow", "child2", None))
        item = self.children_listWidget.item(2)
        item.setText(_translate("MainWindow", "child3", None))
        self.children_listWidget.setSortingEnabled(__sortingEnabled)
        self.add_child_pushButton.setText(_translate("MainWindow", "إضافة طفل", None))
        self.child_date_of_birth_label.setText(_translate("MainWindow", "تاريخ الميلاد:", None))
        self.label_15.setText(_translate("MainWindow", "الاسم:", None))
        self.label_16.setText(_translate("MainWindow", "اللقب:", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "محتاج خصوصي في:", None))
        self.english_course_checkBox.setText(_translate("MainWindow", "أنجليزي", None))
        self.arabic_course_checkBox.setText(_translate("MainWindow", "عربي", None))
        self.math_course_checkBox.setText(_translate("MainWindow", "رياضيات", None))
        self.islamic_course_checkBox.setText(_translate("MainWindow", "دراسات إسلامية", None))
        self.science_course_checkBox.setText(_translate("MainWindow", "علوم", None))
        self.computer_course_checkBox.setText(_translate("MainWindow", "حاسوب", None))
        self.child_study_level_comboBox.setItemText(0, _translate("MainWindow", "New Item", None))
        self.child_study_level_comboBox.setItemText(1, _translate("MainWindow", "New Item", None))
        self.child_study_level_comboBox.setItemText(2, _translate("MainWindow", "New Item", None))
        self.child_study_level_label.setText(_translate("MainWindow", "المستوى الدراسي", None))
        self.child_need_transportation_checkBox.setText(_translate("MainWindow", "محتاج للمواصلات", None))
        self.label_20.setText(_translate("MainWindow", "تقدبر العام الماضي", None))
        self.grade_last_year_comboBox.setItemText(0, _translate("MainWindow", "New Item", None))
        self.grade_last_year_comboBox.setItemText(1, _translate("MainWindow", "New Item", None))
        self.grade_last_year_comboBox.setItemText(2, _translate("MainWindow", "New Item", None))
        self.label_11.setText(_translate("MainWindow", "الهوايات:", None))
        self.save_child_pushButton.setText(_translate("MainWindow", "حفظ", None))
        self.save_woman_pushButton.setText(_translate("MainWindow", "حفظ", None))
        self.available_time_comboBox.setItemText(0, _translate("MainWindow", "New Item", None))
        self.available_time_comboBox.setItemText(1, _translate("MainWindow", "New Item", None))
        self.available_time_comboBox.setItemText(2, _translate("MainWindow", "New Item", None))
        self.label_21.setText(_translate("MainWindow", "الفترة:", None))

